### ISSUE TITLE
QDarkStyle issue on Mac for status bar

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#9120]
## Problem Description

On MacOS the Status bar  for the Dark style looks like:
<img width="1440" alt="Screen Shot 2019-04-05 at 20 00 53" src="https://user-images.githubusercontent.com/3627835/55662886-94f53e80-57dd-11e9-8d56-bd25e4b6101d.png">

### What is the expected output? What do you see instead?

It should look either like this:
<img width="1440" alt="Screen Shot 2019-04-05 at 19 48 38" src="https://user-images.githubusercontent.com/3627835/55662892-9de61000-57dd-11e9-99b8-59d3f3eaca77.png">

Or like this:

@ccordoba12 @dpizetta, is this an option we could consider as a default on QDarkStyle?

It would require something like

```css
/* QStatusBar ------------------------------------------------------------- */

QStatusBar {
    background: #32414B;
    border: 1px solid #32414B;
}

QStatusBar QLabel {
    background-color: transparent;
}
```

<img width="1440" alt="Screen Shot 2019-04-05 at 19 50 33" src="https://user-images.githubusercontent.com/3627835/55662893-a2122d80-57dd-11e9-8be7-8f5e4bbbd50c.png">
